### ISSUE TITLE
Unable to set initial value on Radio button

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#10]
In the Form component, providing a value for a radio button does not set the value for the control. 

Components.Form({
                    el: targetElement,
                    rows: [
                             {
                            control: {
                                label: "Primary or Secondary:",
                                name: "LanguageLevel",
                                type: Components.FormControlTypes.Radio,
                                items: [{ label: "Primary", name: "Primary" },
                                { label: "Secondary", name: "Secondary"}],
                                onValidate: (control, value) => {
                                    //Validate that value is selected
                                    return value ? true : false;
                                },
                                errorMessage: "Select a valid Language Level"
                            } as IFormControlProps
                        }
                   ],
 value: record ? {
                        LanguageLevel: "Primary",
                    } : {}
})

**Comment by gunjandatta** [comment]
The checkbox group component didn't have the value property defined. I'll add that in now to match the input group and dropdown list.

**Comment by gunjandatta** [comment]
Fixed in v1.2.0.
