### ISSUE TITLE
People Picker Component Not Providing SPUserID

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#27]
After added a People Picker Component to a page, selecting a person, and using the getValue function, the EntityData.SPUserID is not populated for the selected person. 

```typescript
let peoplePickerValues = _peoplePicker.getValue();

peoplePickerValues.forEach((value) => {
     value.EntityData.SPUserID;
})
```

**Comment by gunjandatta** [comment]
I updated the code to check for the SPUserID after selection, to ensure it's available. Fixed in v3.0.8.
