### ISSUE TITLE
People Picker isReadOnly Property Styling

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#29]
When selecting a person using the Components.IFormControlPropsPeoplePicker, the html generated could use some minor changes. The parent div container for the selected people buttons that appear might be better off with the "position" set to "relative". Additionally, the people buttons could use a margin-bottom for when the buttons wrap to a new line. Example desired HTML:

```html
<div style="position: relative;" class="bs">
   <a href="#" role="button" disabled="true" data-toggle="popover" data-trigger="focus" class="mr-1 mb-1 btn btn-sm btn-primary" ...
```

**Comment by gunjandatta** [comment]
Update to the latest and let me know if it's still an issue.

**Comment by gunjandatta** [comment]
I updated the position to be relative in v3.3.3.
