### ISSUE TITLE
className Not Appending Class to Dropdown Control

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#3]
When adding a dropdown control using the Form component, including the className does not add the class to the control. Example:

`{
                                    control: {
                                        label: "Reason Not Tested:",
                                        name: "ReasonNotTested",
                                        type: Components.FormControlTypes.Dropdown,
                                        items: [{ text: "No Tester Available" }, { text: "Refused Testing" }, { text: "Other" }],
                                        className: "d-none"
                                    } as IFormControlPropsDropdown
                                },`

**Comment by gunjandatta** [comment]
This bug should be reported in the [gd-bs](https://github.com/gunjandatta/gd-bs/issues). I fixed the issue, and updated this library as well.

Target v1.0.3

**Comment by gunjandatta** [comment]
I added a new property to the FormControl "controlClassName". This will be set on the control's element.

Target v1.0.4
