### ISSUE TITLE
List Form Field - Display Name

### ISSUE THREAD

**Issue by gudatta** [gunjandatta/sprest-bs#34]
The content type field link is set as:

{ Name: "Author", DisplayName: "Traveler" },

but the list form is still using "Created By" as the display name.

**Comment by gunjandatta** [comment]
Fixed in v4.0.4.

**Comment by gunjandatta** [comment]
I've kept the code to use the readonly and required properties, but the "DisplayName" value returned may match the internal name which isn't correct. I recommend you use the onControlRendering event to override the display name in the form.
