### ISSUE TITLE
Radio Buttons returning boolean for form value

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#4]
The radio button form control is returning a boolean value in the form.getValues(), instead of the selected value. Example:

`{
                            control: {
                                label: "Primary or Secondary:",
                                name: "example",
                                type: Components.FormControlTypes.Radio,
                                items: [{ label: "Primary", name:"Primary", }, { label: "Secondary", name:"Secondary" }],
                                 onValidate: control => {
                                    _form.getValues()["example"].value; //<-- only returns boolean 
                                    control.value; //<-- returns selected value correctly
                                    ...
                                },
                                errorMessage: "Select a valid Language Level"
                            } as IFormControlProps
}`

**Comment by gunjandatta** [comment]
Thank you for reporting this bug. I've fixed this issue.

Target v1.1.5.
