### ISSUE TITLE
Feature Request: Add Option to Restrict People Picker to SP Group

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#41]
When creating a people picker, I need the ability to restrict the people available to only a single SharePoint group. I think you can update the PeoplePicker.ts, function searchUsers, to add an optional parameter for a SharePoint Group ID, and then user that param in the Search().clientPeoplePickerSearchUser query. Intellisense on that function shows that a SharePointGroupID is an available query parameter. Suggested code update below:

```javascript
    let searchUsers = (el: HTMLElement, searchText: string, searchAll: boolean = true, spGroupID?:number) => {
        // Ensure 3 characters exist
        if (_filterText.length > 2) {
            // Search for the user
            Search().clientPeoplePickerSearchUser({
                MaximumEntitySuggestions: props.maxResults || 25,
                PrincipalSource: searchAll ? SPTypes.PrincipalSources.All : SPTypes.PrincipalSources.UserInfoList,
                PrincipalType: props.allowGroups ? SPTypes.PrincipalTypes.All : SPTypes.PrincipalTypes.User,
                QueryString: _filterText, 
                SharePointGroupID:spGroupID
            }).execute((search) => {
            ...
```

**Comment by gunjandatta** [comment]
I added the property and implemented the feature request. You'll find this in v7.7.5.

**Comment by sky-gregory** [comment]
One more modification might be required. That new parameter doesn't make it to the PeoplePicker object. On line 330 of the PeoplePicker.ts file, the groupId will need to be passed.  The code section will likely need to look like the following:

```javascript
        picker = PeoplePicker({
            allowGroups: props.allowGroups,
            className: props.className,
            el: ctrl.el,
            label: props.label,
            maxResults: props.maxResults,
            multi: props.multi,
            placeholder: props.placeholder,
            readOnly: props.isReadonly,
            searchLocal: props.searchLocal,
            value: props.value,
            groupId: props.groupId
        });
```

The groupId prop also doesn't exist on IFormControlPropsPeoplePicker, so it will probably need to be added there too.

**Comment by sky-gregory** [comment]
One additional change: 
Need to add the groupId prop to @types/components/peoplePicker.d.ts.

```javascript
export interface IFormControlPropsPeoplePicker extends IFormControlProps {
    allowGroups?: boolean;
    maxResults?: number;
    multi?: boolean;
    placeholder?: string;
    searchLocal?: boolean;
    value?: string | number | Types.IPeoplePickerUser | Array<string | number | Types.IPeoplePickerUser>;
    groupId?: number;
}
```

I confirmed in a local build that these last two changes enable the functionality.
