### ISSUE TITLE
People Picker to auto scroll in screen

### ISSUE THREAD

**Issue by zeroClassSOLDIER** [gunjandatta/sprest-bs#47]
We've noticed in modals that if the People Picker is towards the bottom, and if it is returning names, they will appear out of view unless you scroll down (that is if the modal is scrollable). Is there a recommended way to make the People Picker scrollable or is it a framework setting?

**Comment by gunjandatta** [comment]
v8.7.7 has the fix for the people picker. It should automatically update based on the available space.
