### ISSUE TITLE
Setting Initial Value for Radio Button Not Working

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#5]
When creating a radio button and attempting to set an initial value, the value is not selected.

Ex 1: 

`control: {
                                label: "Primary or Secondary (for Posts with Multiple Languages):",
                                name: "LanguageLevel",
                                type: Components.FormControlTypes.Radio,
                                items: [{ label: "Primary", name: "Primary", isSelected: record ? record.LanguageLevel == "Primary" : true },
                                { label: "Secondary", name: "Secondary", isSelected: record ? record.LanguageLevel == "Secondary" : false }],
                                onValidate: control => {
                                    return control.value;
                                },
                                errorMessage: "Select a valid Language Level"
                            } as IFormControlProps`

Ex 2:

`
Components.Form({
                    el: targetElement,
                    rows: [ ... ],
                    value: record ? {
                        LanguageLevel: record.LanguageLevel //<-- 
                    } : {}
`

**Comment by gunjandatta** [comment]
The correct property is "checked", but I'm going to change it to "isSelected" to better match the rest of the other component item properties. Thanks for this feedback.

Target v1.1.5
