### ISSUE TITLE
Text Box Controls Not Styled When Invalid

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#8]
The Textbox form component does not turn red when the textbox is set to invalid.

**Comment by gunjandatta** [comment]
Thank you for reporting this issue. Please send a code example, I'm not able to recreate this issue.

**Comment by sky-gregory** [comment]
Code example from within a Form Component: 

`{
                            control: {
                                label: "Reason Not Tested Explanation:",
                                name: "ReasonNotTestedExplanation",
                                type: Components.FormControlTypes.TextField,
                                placeholder: "Explain the reason not tested",
                                onValidate: ctrl => {
                                    let formValues = _form.getValues();
                                    let controlValue = formValues["ReasonNotTestedExplanation"];
                                        if (controlValue && controlValue.length > 0)
                                            return true;
                                        else
                                            return false;
                                },
                                errorMessage: "Provide a reason for not testing"
                            } as IFormControlPropsTextField
                        },`

**Comment by gunjandatta** [comment]
Here is what I recommend you do:

```
{
{
    control: {
        label: "Reason Not Tested Explanation:",
        name: "ReasonNotTestedExplanation",
        type: GD.Components.FormControlTypes.TextField,
        placeholder: "Explain the reason not tested",
        onValidate: function(ctrl, value) {
            if (value && value.length > 0)
                return true;
            else
                return false;
            },
        errorMessage: "Provide a reason for not testing"
    }
}
```

The difference is the onValidate method. Use the "value" property passed into it.

**Comment by sky-gregory** [comment]
The error message comes out correctly, but the red outline on the field does not appear like it does with other control types

**Comment by sky-gregory** [comment]
Nevermind... the css from a competing style sheet is overriding :\
