### ISSUE TITLE
Radio Button not Returning Control Value

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest-bs#9]
In the onValidate function, a radio button isn't returning the control's selected value

Ex:

`{
                            control: {
                                label: "Primary or Secondary (for Posts with Multiple Languages):",
                                name: "LanguageLevel",
                                type: Components.FormControlTypes.Radio,
                                items: [{ label: "Primary", name: "Primary" },
                                { label: "Secondary", name: "Secondary"}],
                                onValidate: control => {
                                    //Validate that value is selected
                                    return control.value ? true : false; //<-- Always returns undefined
                                },
                                errorMessage: "Select a valid Language Level"
                            } as IFormControlProps
                        }`

**Comment by gunjandatta** [comment]
I'm not able to reproduce this in v1.1.9. The value for the radio is the "item" which was working.

```
{
    control: {
        label: "Reason Not Tested Explanation:",
        name: "ReasonNotTestedExplanation",
        type: GD.Components.FormControlTypes.TextField,
        placeholder: "Explain the reason not tested",
        onValidate: function(ctrl, value) {
            if (value && value.length > 0)
                return true;
            else
                return false;
            },
        errorMessage: "Provide a reason for not testing"
    }
}
```
